name: POE2 Release

on:
  push:
    tags:
      - "POE2-*"
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Install PoeFilterX-NPM
        run: npm install -g git+https://github.com/SteffenBlake/PoeFilterX-NPM

      - name: Build for POE2
        run: npm run build-poe2

      - name: Upload Release Assets
        uses: actions/upload-artifact@v3
        with:
          name: POE2-output
          path: ./output

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: |
            Automated release for tag ${{ github.ref_name }}.
          draft: false
          prerelease: false

      - name: Upload Artifacts to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./output/*
          tag: ${{ github.ref_name }}
          file_glob: true
